name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # Docker image with Cypress pre-installed
    # https://github.com/cypress-io/cypress-docker-images/tree/master/included
    container: cypress/included:3.8.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install npm packages
        run: npm install
      - name: Run Regression tests
        run: npm run cy:test
